cmake_minimum_required(VERSION 3.5)

macro(define_plaform_settings)
	if( PLATFORM_WINDOWS)
		add_compile_options(/Zi)
		add_compile_options($<$<CONFIG:DEBUG>:/Od> $<$<NOT:$<CONFIG:DEBUG>>:/Ox>)
		add_compile_options(/Ob2)
		add_compile_options($<$<NOT:$<CONFIG:DEBUG>>:/Oi>)
		add_compile_options(/Ot)
		add_compile_options($<$<NOT:$<CONFIG:DEBUG>>:/GT>)
		add_compile_options(/GF)

		if( PLATFORM_WINDOWS AND RUNTIME_TYPE STREQUAL "mt")
			add_compile_options($<$<CONFIG:DEBUG>:/MTd> $<$<NOT:$<CONFIG:DEBUG>>:/MT>)
		elseif( PLATFORM_WINDOWS AND RUNTIME_TYPE STREQUAL "md")
			add_compile_options($<$<CONFIG:DEBUG>:/MDd> $<$<NOT:$<CONFIG:DEBUG>>:/MD>)
		endif()
		add_compile_options(/Gy)
		add_compile_options(/fp:fast)
		replace_compile_flags("/GR" "/GR-")
		add_compile_options(/W4)
		add_compile_options(/WX)
		add_exe_linker_flags(/DEBUG)
		add_exe_linker_flags(/MAP)
		replace_linker_flags("/INCREMENTAL" "/INCREMENTAL:NO" debug)
		add_compile_options(/MP)
		add_compile_options(-D_HAS_EXCEPTIONS=0)
		replace_linker_flags("/debug" "/DEBUG" debug)
		replace_linker_flags("/machine:x64" "/MACHINE:X64")
		add_compile_options(/wd4505)
		add_compile_options(-D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE)
		add_compile_options(-DSECURITY_WIN32)

		MARK_AS_ADVANCED(embree_DIR)

		SET(EMBREE_VERSION 3.2.3)
		SET(EMBREE_VERSION_MAJOR 3)
		SET(EMBREE_VERSION_MINOR 2)
		SET(EMBREE_VERSION_PATCH 3)
		SET(EMBREE_VERSION_NOTE "")

		SET(EMBREE_MAX_ISA NONE)
		SET(EMBREE_ISA_SSE2  ON)
		SET(EMBREE_ISA_SSE42 ON)
		SET(EMBREE_ISA_AVX ON) 
		SET(EMBREE_ISA_AVX2  ON)
		SET(EMBREE_ISA_AVX512KNL OFF)
		SET(EMBREE_ISA_AVX512SKX ON)

		SET(EMBREE_BUILD_TYPE Release)
		SET(EMBREE_ISPC_SUPPORT ON)
		SET(EMBREE_STATIC_LIB OFF)
		SET(EMBREE_TUTORIALS ON)

		SET(EMBREE_RAY_MASK OFF)
		SET(EMBREE_STAT_COUNTERS OFF)
		SET(EMBREE_BACKFACE_CULLING OFF)
		SET(EMBREE_FILTER_FUNCTION ON)
		SET(EMBREE_IGNORE_INVALID_RAYS OFF)
		SET(EMBREE_TASKING_SYSTEM TBB)

		SET(EMBREE_GEOMETRY_TRIANGLE ON)
		SET(EMBREE_GEOMETRY_QUAD ON)
		SET(EMBREE_GEOMETRY_CURVE ON)
		SET(EMBREE_GEOMETRY_SUBDIVISION ON)
		SET(EMBREE_GEOMETRY_USER ON)
		SET(EMBREE_RAY_PACKETS ON)
	else()
		message(FATAL_ERROR "Unknown platform!")
	endif()
endmacro()
